/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinlei_hellojni_Hello */

#ifndef _Included_com_jinlei_hellojni_Hello
#define _Included_com_jinlei_hellojni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinlei_hellojni_Hello
 * Method:    sayhello
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jinlei_hellojni_Hello_sayhello
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jinlei_hellojni_Hello
 * Method:    printString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jinlei_hellojni_Hello_printString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
