/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniDemo */

#ifndef _Included_JniDemo
#define _Included_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniDemo
 * Method:    hello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JniDemo_hello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
